site_name: Java Notes
site_url: https://github.com/thearjun/java-notes
docs_dir: docs/
theme:
  name: material
  favicon: 'assets/images/java.png'
  logo: 'assets/images/java.png'
  palette:
    primary: teal
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    # - header.autohide
    - navigation.tabs
    # - navigation.instant
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2020 Arjun Adhikari
repo_url: https://github.com/thearjun/java-notes
repo_name: thearjun/java-notes
edit_uri: "https://github.com/thearjun/java-notes/tree/mkdocs/docs/"
markdown_extensions:
  - meta
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.highlight:
      linenums_style: pymdownx.inline
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
google_analytics:
  - UA-123982482-1
  - auto
extra:
  generator: false
  disqus: thearjun
  manifest: manifest.webmanifest
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/thearjun
    - icon: fontawesome/brands/github
      link: https://github.com/thearjun
    - icon: fontawesome/solid/envelope
      link: mailto:mailarjunadhikari@gmail.com
    - icon: fontawesome/solid/user
      link: https://www.upwork.com/freelancers/~017a123f27939046d8

extra_javascript:
  - assets/javascripts/extra.js
  - assets/javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - assets/stylesheets/extra.css

plugins:
  - search
  - macros:
      include_dir: docs
nav:
  - README.md
  - Basics: 
      - introduction/README.md
      - Identifiers: introduction/IDENTIFIER.md
      - Reserved Words: introduction/ReservedWord.md
      - Data Types: introduction/DataTypes.md
  - Arrays: 
      - Introduction: array/README.md
      - Matrix Representation: array/matrixRepresentation/README.md
      - Array Representation 01: array/arrayRepresentation01/README.md
      - Array Representation 02: array/arrayRepresentation02/README.md
      - Examples: array/extra.md
  - Networking:
      - Introduction: networking/README.md
      - URL: networking/URL/README.md
      - InetAddress: networking/InetAddress/README.md
      - URLConnection: networking/URLConnection/README.md
      - HTTP URL Connection: networking/HTTPURLConnection/README.md
      - Check Internet Conneciton: networking/checkInternetConnection/README.md
      - WHOIS Implementation: networking/whoisImplementation/README.md
      - InetAddress: networking/InetAddress/README.md
      - Socket Programming:
        - Introduction: networking/SocketProgramming/README.md
        - Server to Client Mesaging: networking/ServerToClient/README.md
        - Client to Server Mesaging: networking/chatApplication/README.md
        - Dual Connection: networking/dualConnection/README.md
        - Connection Less: networking/ConnectionLess/README.md
        - UDP Messaging: networking/UDPMessaging/README.md
  - Exams:
      - Programming: exams/examQuestions/ProgrammingQuestions.md
      - General: exams/examQuestions/README.md
